 
################

#   Target

################

 

PROGRAMS_spu          := tema4_spu

 

LIBRARY_embed          := lib_tema4_spu.a

 

 

################

#   Local Defines

################

CFLAGS		:= -DDEBUG_
 
IMPORTS		:= -lm
 

################

#   buildutils/make.footer

################

 

ifdef CELL_TOP

            include $(CELL_TOP)/buildutils/make.footer

else

            include ../../../../buildutils/make.footer

endif
